name: Missiles
version: 1.0
author: Vilevar
main: be.vilevar.missiles.Main
api-version: 1.16
commands:
 missile:
  description: launch the game
 missile_world:
  description: Create a world with a lot of villages
 discharge:
  description: Discharge your gun